<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\TerminoCondicion;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class TerminosCondicionesSeeder extends Seeder
{
    public function run()
    {
        // Desactivar llaves foráneas para poder limpiar la tabla sin errores
        Schema::disableForeignKeyConstraints();
        DB::table('terminos_condiciones')->truncate();
        Schema::enableForeignKeyConstraints();

        $texto = "<strong>Acuerdo Responsabilidad</strong><br>
<strong>RELEVO/DESGARGO DE RESPONSABILIDAD</strong><br>
<strong>NINJA PARK, C.A. VALENCIA</strong><br><br>
Ninja Park es el lugar perfecto para nunca dejar de jugar y disfrutar junto a tu familia y amigos, enfocados en proveer diversión para toda la familia. Somos una compañía de trampolines y parques indoor, ofrecemos actividades que van desde saltos regulares en trampolines a juegos de obstáculos como el playground con sus toboganes, balancines, acceso a castillos, piscinas de pelotas, piscinas de goma espuma, canchas de basket, aventuras en arnés, puentes colgantes entre otros, de aquí en adelante denominadas como las “Atracciones”. Para nosotros la seguridad es una prioridad; es por eso que Ninja Park está diseñado con los controles de calidad que corresponden, tomando en cuenta que por la energía y el actuar propio de los niños y adolescentes pudieran ocurrir incidentes o accidentes menores de manera fortuita que no tengan que ver con el mantenimiento ni con el funcionamiento de las instalaciones, dadas las características de las Atracciones. En tal sentido, Ninja Park establece sus Normas de Seguridad, así como el Reglamento Interno para cada una de sus Atracciones. Por lo tanto, el cliente que visita las atracciones de Ninja Park debe comprender que existen riesgos en el uso de las Atracciones, por consiguiente, es responsable de seguir todas las normas y reglas de seguridad para evitar posibles lesiones.<br><br>
<strong>Advertencia:</strong> Lea cuidadosamente este acuerdo de participación y formulario de descargo de responsabilidad, donde asume de forma voluntaria los riesgos y posibles consecuencias que puedan derivarse de la utilización de las Atracciones. No firme este acuerdo a menos que lo haya leído cuidadosamente en su totalidad y entienda el contenido del presente. Las actividades recreativas en las Atracciones pueden resultar en lesiones graves. Entre los riesgos por el uso de las atracciones del parque, se identifican riesgos físicos y/o riesgos emocionales, como parálisis, daños a usted mismo y/o a otros, resbalones y caídas, aterrizaje incorrecto después de saltar, colisiones con objetos fijos, objetos en movimiento y/u otras personas; que pueden resultar en esguinces, fracturas, roturas, raspones, dislocaciones y lesiones en la cabeza, espalda y/o cuello.<br><br>
En consideración a los servicios de Atracciones brindados por Ninja Park y mi deseo de participar en los mismos, ya sea por mi mismo o en representación de mi acompañante menor de edad, acordamos lo siguiente:<br><br>
Este acuerdo de participación y descargo de responsabilidad de aquí en adelante denominado como el “Acuerdo” se celebra entre Ninja Park y el participante, mayor de edad, (padre, representante o responsable) de aquí en adelante denominado como el “Cliente”, que está ejecutando este Acuerdo personalmente, en nombre de sí mismo y de todos y cada uno de los hijos y/o acompañantes menores especificados a continuación (colectivamente denominados como los “Usuarios”).<br><br>
El abajo firmante en mi nombre, mi(s) hijo(s), acompañante(s) y/o representado(s) menor(es) de edad, de quien(es) soy principal y único responsable, por la presente ACEPTO lo siguiente:<br>
El abajo firmante en mi nombre, mi(s) hijo(s) / y/o representado (s) menor(es), de quien soy nombrado tutor por la presente ACEPTO lo siguiente:<br><br>
• <strong>PARTICIPACIÓN VOLUNTARIA.</strong> Me comprometo a utilizar las instalaciones y Atracciones de forma segura y responsable, y acepto cumplir con las reglas y normas de Ninja Park y las instrucciones dadas por los empleados, por lo que reconozco que dichas reglas, normas e instrucciones están destinadas a promover mi seguridad y la de los demás; el incumplimiento o negativa de acatar dichas reglas, normas e instrucciones puede dar lugar a que me suspendan de manera inmediata del derecho a utilizar las instalaciones de Ninja Park y sus Atracciones, sin derecho a devolución de los pagos realizados; y en caso de accidente o lesión: a) debo informar inmediatamente de la lesión o la de mi(s) representado(s) al personal de Ninja Park y bajo ninguna circunstancia abandonaré las instalaciones sin hacer la debida notificación, b) paralizaré toda participación en las actividades del parque en el momento del accidente o lesión, c) autorizo a los empleados de Ninja Park a prestar los primeros auxilios e incluso llamar a una ambulancia en caso de ser necesario; d) acepto asumir, a mi cargo, todos los costos y gastos de atención médica de emergencia y transporte que se pudieren generar con motivo de la lesión o accidente acaecido en las Atracciones.<br><br>
• <strong>RECONOCIMIENTO DE REGLAS.</strong> Declaro saber que cada una de las Atracciones tiene normativas internas, y comprendo que existen riesgos en el uso de las instalaciones, por consiguiente, soy responsable de actuar con diligencia, seguir las medidas de seguridad y reglamentos del parque en cada una de las Atracciones. Ninja Park se responsabiliza de informarme de todas las medidas de seguridad, las cuales son explicadas en este Acuerdo; y soy el responsable de instruir al(os) menor(es) de edad a mi cargo en el cumplimiento de normas, reglas e instrucciones dadas por los empleados.<br><br>
• <strong>ACEPTACIÓN DE RIESGO.</strong> Se y comprendo completamente que la participación en las Atracciones de Ninja Park implica riesgos y peligros inherentes: a) reconozco que el uso indebido de las Atracciones como el rebote doble (más de una persona por trampolín), el dar volteretas y piruetas, correr, rebotar contra las paredes, aterrizar mal al saltar fuera del trampolín, resortes o en el marco del mismo, chocar contra otras personas; así como el uso indebido del resto de las Atracciones en general, son actividades peligrosas y pueden causar lesiones graves, y estas actividades se llevan a cabo por cuenta y riesgo de los Usuarios; b) reconozco y acepto que por las características propias del parque, pueden ocurrir incidentes y accidentes menores fortuitos de distinta índole, que pueden resultar en lesiones corporales graves; c) Manifiesto estar consciente de estos riesgos y acepto que Ninja Park, en caso de ocurrir algún accidente, solo está obligado a prestar servicios básicos de primeros auxilios dentro sus instalaciones y luego correrán por mi cuenta todos los gastos que sean necesarios para atender la emergencia en cualquier centro asistencial de salud de mi elección, liberando a Ninja Park de cualquier responsabilidad en este sentido.<br><br>
• <strong>LIBERACIÓN.</strong> Reconozco como buena y valiosa contraprestación el derecho a utilizar y participar voluntariamente en las Atracciones de Ninja Park, en tal sentido libero a Ninja Park de toda responsabilidad por cualquier incidente o accidente causado por incumplimiento del reglamento y sus normativas. Acuerdo renunciar por completo y para siempre, eximir y descargar a Ninja Park de todos y cada uno de los reclamos, acciones, causas de acción, demandas, juicios, daños (incluidos los compensatorios, generales, físicos, morales, especiales, consecuentes, ejemplares y punitivos), responsabilidad u obligaciones de cualquier naturaleza o tipo, ya sea conocido en el momento en que me retiro de las instalaciones de Ninja Park o que pueda surgir o llegar a conocerse en un futuro.<br><br>
• <strong>APTITUD PARA PARTICIPAR.</strong> Declaro expresamente que los Usuarios gozan de buena salud y condición física adecuada para utilizar las Atracciones de Ninja Park, además declaro que los Usuarios a) no tienen discapacidades, dolencias o impedimentos físicos, mentales o cognitivos, entre otros; embarazo, problemas ortopédicos, de espalda; problemas del corazón o respiratorios que puedan afectar su capacidad para utilizar las Atracciones, b) no están bajo la influencia del alcohol, drogas ilícitas, medicamentos u otras sustancias que alteren el estado de ánimo y que puedan afectar su capacidad para utilizar las Atracciones, c) asumo la responsabilidad exclusiva y total de determinar la suficiencia de su salud, estado físico y capacidad para utilizar las Atracciones.<br><br>
• <strong>DIVULGACIÓN DE VIDEOS, FOTOS E IMÁGENES.</strong> Acepto, consiento y autorizo el derecho exclusivo y doy el permiso para usar de manera legal las fotos, imágenes y videos capturados en las instalaciones de Ninja Park, de mi imagen y/o la de los menores de edad por los cuales soy responsable; para todos los fines publicitarios en la Web, redes sociales, material impreso, pantallas electrónicas, televisivos, gigantografías con fines publicitarios y comerciales, sin compensación alguna. A excepción, de que el cliente haya solicitado explícitamente y por escrito que no desea que su imagen sea divulgada al momento de ingresar al parque.<br><br>
<strong>CONSENTIMIENTO DEL PADRE, REPRESENTANTE O RESPONSABLE</strong><br>
(El Cliente)<br><br>
• He leído, entiendo y acepto los términos de este Acuerdo de descargo de responsabilidad de manera incondicional en todos sus términos, declaraciones, garantías, avisos, representaciones y liberaciones en mi nombre y en el de mi familia o representados ante las instalaciones de Ninja Park, cuyos nombres aparecen aquí.<br><br>
Este Acuerdo se firma electrónicamente, en persona por medio de las Tablets que se encuentran en los parques, a través de la página Web de Ninja Park o cualquier otro método reconocido y legal de ejecución de un acuerdo vinculante.<br><br>
El uso de las instalaciones de Ninja Park se considerará una aceptación de todos los términos y condiciones de este Acuerdo.";

        TerminoCondicion::create([
            'version'   => '1.0',
            'contenido' => $texto,
            'activo'    => true
        ]);
    }
}
